project:
  type: website
  output-dir: C:/Users/adelync.stu/Documents/FCOR 599/E-Portfolio/E-Portfolio-main/E-Portfolio-main/E-Portfolio

website:
  title: "Your E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content & Deliverables

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

